### ISSUE TITLE
Metrolist submission form bugs

### ISSUE THREAD

**Issue by ebshrier** [CityOfBoston/boston.gov-d8#2529]
There are several bugs that need to be fixed on the Metrolist submission form. You can access the form here:
https://www.boston.gov/form/metrolist-listing?token=FI3igpCq4Ljlowp0GE5yMiC67HiNRoC6fpQrKSL223I

Note: page numbers relate to progress bar at top of form.
Browser: Chrome

Pg 1:
- Notification popup covers text and cannot be closed. It appears across all pages. see submission1 
- Not clear what was found or why, especially bc I have to select my contact info. 
- _Solution_: notice should be removed altogether. -OR- allow user to close it. 
- **Complete**

pg 2
- scroll down (with mouse wheel, past bottom) makes page flutter.

pg 5:
- What does "Add more units" do? You cannot add bedrooms, etc as above. see submission2
- _Solution_: This should allow user to add additional units. 
- **Complete**

pg 7:
- When you click "submit" there is no indication that anything was sent. 
- If you click resubmit on the form, duplicate development records are created in Salesforce.
- Submit confirmation message sometimes appears but dev units not saved in Salesforce.
- Sometimes no confirmation message but development is still created (dev units do not get saved).
- Sometimes spins for several minutes before message appears. Not sure if you close window before submission completes if that stops integration with SF.
- _Quick fix_  Provide onscreen notification popup that submission was sent. (need ability to close popup)
- _Better fix / enhancement_: on submit, send user to new page indicating successful submission, and giving user option to start a new submission or close the form.

1. Inconsistent behavior. Screen does not function same way twice. 
2. Boston.gov menu options sometimes pop up unexpectedly (on hover or click on previous button) and kick you out of form.
3. **PDF attachments seems to break it. Adding website or leaving field blank seems to work. Sometimes PDF docs block submission, sometimes not** This appears to be primary issue.

Other notes:
When Beth keys it in for POs, generally keys it in directly into SF
Dev units and building info loaded into form upon request, and is saved in that instance of the form. Data entered into form by user is saved as parameters, so every time that instance of form is used, all the data persists, even if the record was not created in SF.
Data integration with SF slow. You have to wait a few minutes for changes in SF to propagate to new form request.

**Comment by ebshrier** [comment]
![Image](https://user-images.githubusercontent.com/104999302/172901587-e2578938-7029-4718-99ea-e868a7a71268.PNG)
![Image](https://user-images.githubusercontent.com/104999302/172901588-bf980a6c-3aaa-44fb-9bbe-bee4f9937886.PNG)

**Comment by duffy-james** [comment]
These tickets are also related: #2494 and #2493

**Comment by davidrkupton** [comment]
This is now on ci [https://d8-ci.boston.gov:](http://d8-ci.boston.gov/)

https://d8-ci.boston.gov/departments/neighborhood-development/metrolist/metrolist-listing-form

**Comment by ebshrier** [comment]
Testing notes:

Resolved issues:
- Initial "error" message no longer appears.
- Styling looks good throughout. Drawers on summary screen are good.
- Apostrophe doesn't cause submission error. 

Open Issues:
- Step 5 Unit Details: The example "View Screenshot" image link is broken. 
(https://user-images.githubusercontent.com/104999302/176711136-3323195c-a93b-4442-af8d-20a6dedfa0b0.PNG)
- Step 2: When entering phone number, an error is thrown saying formatting is incorrect. When screen reloads, number has been formatted properly (with no input from user) and can be successfully resubmitted. I didn't experience this issue in earlier testing.
- Same issue exists on Application deadline field (step 6)
- After clicking submit, there was no confirmation message that listing was submitted. (step 7)

Thanks

**Comment by duffy-james** [comment]
@ebshrier one note on the broken image error -- that may be the result of you being on a test environment. Can you confirm that's also not working on production?

**Comment by ebshrier** [comment]
@duffy-james Good call. Alas, image is broken in production as well. 
@davidrkupton The pdf issue is the biggest blocker at the moment. If this issue can be resolved before next wednesday's release that would be great. Let me know if you need more info.
thanks

**Comment by davidrkupton** [comment]
Hi @ebshrier , I think the screenshot in the last comment is from prod, so we expect the error messages to be a bit funky until we put the code from CI to Prod.
I would test on CI if I were you, as that is where I am continuing to add new code as I resolve issues.

**Comment by davidrkupton** [comment]
Hi @ebshrier could you please supply a copy of the image you would like on step 5 of the metrolist form.  The one which should appear here:
![image](https://user-images.githubusercontent.com/4700050/177336254-027dce07-8625-4e6b-adef-2e02a806e4b4.png)

**Comment by davidrkupton** [comment]
Hi @ebshrier I also think the PDF issue is solved on the CIU version.  I was just able to upload a PDF there.  Are you trying to upload one which is >25MB?

**Comment by duffy-james** [comment]
@ebshrier can you answer these questions when you get a moment:

1. Are you testing on the [CI version of the Metrolist form](https://d8-ci.boston.gov/departments/neighborhood-development/metrolist/metrolist-listing-form)?
2. Can you share the screenshot of the image you're [expecting to see here](https://user-images.githubusercontent.com/104999302/176711136-3323195c-a93b-4442-af8d-20a6dedfa0b0.PNG)? We have no way of knowing what that image should be, unfortunately. We can also remove that for now.
3. Is the pdf you're looking to upload bigger than 25MB? If it is, you'll see the validation error that David notes.

**Comment by ebshrier** [comment]
Hi @davidrkupton @duffy-james 
I don't actually know what or where that image is. I believe it was working recently, but I'll have to ask around to see if anyone knows what it should be. 
I was testing on the CI version. I did note an error in the production form last week that I hadn't seen before, but it may be addressed by the fixes currently in CI. 
My testing has been with pdfs smaller than 25MB, and the business team has consistently seen problems with the application form when pdfs smaller than 25MB are attached.
Thanks

**Comment by ebshrier** [comment]
Never the mind. Here's an image you can use.


![2529UnitExample](https://user-images.githubusercontent.com/104999302/177365150-332f6cbf-c3f5-432e-bd6f-df0646219e7f.PNG)

**Comment by ebshrier** [comment]
Hi @davidrkupton  The pdf issue is still there. Just realized you were thinking the problem was with uploading a file to the application. That works. The problem arises when you submit the application - it never goes through to Salesforce.

**Comment by duffy-james** [comment]
@ebshrier thanks for clarifying that point about the pdfs -- David is looking into it now.

**Comment by davidrkupton** [comment]
@ebshrier a question:
When the form is submitted, it looks like 2 things happen: Firstly an email is sent and secondly a record is added to salesforce.

1. Acquia/Drupal upgraded its email system recently and I think that could be why the pdf attachment is not added to the email that is sent.  I can fix that and will do so.
2. It seems that when the form is submitted, a new salesforce case is created. There is limited information adeded to the case, it seems just the contact company.  

Is that correct ?

David.

**Comment by ebshrier** [comment]
Closing ticket. Additional bug tracking will be done in Jira.
