### ISSUE TITLE
Issues with the "list" component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#650]
1. There seems to be a lot of extra options in the "display" drop down here:
![image](https://user-images.githubusercontent.com/7929556/65344261-3d893600-dba5-11e9-9488-b44ebb7b370d.png)

Could we remove "master" and any extraneous options? Also, what's the arguments field (in screenshot above) doing on the page? Is it necessary for content authors to see that?

2. The display styling on the list component looks wrong (not sure if this related to the environment) in these lists: 

Departments:
![image](https://user-images.githubusercontent.com/7929556/65344085-b9cf4980-dba4-11e9-87f1-273408cc2543.png)

News
![image](https://user-images.githubusercontent.com/7929556/65344186-0024a880-dba5-11e9-845f-ce04c721d250.png)

Calendar
![image](https://user-images.githubusercontent.com/7929556/65344406-a53f8100-dba5-11e9-8f58-0cf9851310de.png)
![image](https://user-images.githubusercontent.com/7929556/65344416-affa1600-dba5-11e9-8818-c6279b9270c3.png)

**Comment by reillyzlab** [comment]
Related: https://github.com/CityOfBoston/boston.gov-d8/issues/649

**Comment by davidrkupton** [comment]
Done except for metrolist. Have added to the existing metrolist #678.

**Comment by jimafisk** [comment]
@duffy-james is this issue isolated to "exposed filters" using autocomplete instead of checkboxes? I've reopened this issue that has some additional information: https://github.com/CityOfBoston/boston.gov-d8/issues/547

If the rest of the list component looks ok, I think we're good closing this. Thanks!

**Comment by andrebtlima** [comment]
Related migration issue, the listing component on the Events page is pulling in the Places view instead of the Calendar view. 

http://d8-stg.boston.gov/events

<img width="751" alt="Screen Shot 2019-11-14 at 3 15 10 PM" src="https://user-images.githubusercontent.com/57111927/68892736-a0a0d000-06f1-11ea-9b62-19cfcbe61187.png">

Additionally, the Places view in the listing component isn't allowing you to filter the display, so it's just pulling in all places:

<img width="1397" alt="Screen Shot 2019-11-14 at 3 18 43 PM" src="https://user-images.githubusercontent.com/57111927/68892946-1b69eb00-06f2-11ea-82bc-17336141a56b.png">

In D7:

![image](https://user-images.githubusercontent.com/57111927/68892965-258be980-06f2-11ea-963d-8b411ec1720c.png)

**Comment by andrebtlima** [comment]
On staging, I'm still unable to filter the display for the places view. The only option is "Listing" which I think just pulls in all places.

**Comment by davidrkupton** [comment]
OK this is with Jim.
I think we should close this if all the other items are good.
Lets just make a single issue for the places element - It will reduce time in scanning whenever we open it ... :)
