### ISSUE TITLE
Featured guides component: Grid styling inaccurate and out of order

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#816]
Featured guides component: Grid styling inaccurate and out of order

Example: Digital team test page - http://bostond8dev.prod.acquia-sites.com/digital-team/test-page

![Screen Shot 2019-11-04 at 10 37 01 AM](https://user-images.githubusercontent.com/20731897/68133829-171e2080-feef-11e9-9d7d-e33d57d44f77.png)

**Comment by jimafisk** [comment]
This was fixed via https://github.com/CityOfBoston/boston.gov-d8/pull/712 (for issue https://github.com/CityOfBoston/Iterators/issues/49).

This has since been reverted because the background images were broken. I think we should look at re-implementing because the only way to ensure the correct order is to do this at the parent paragraph level and not the individual node template level that isn't aware of other components on the page.

**Comment by andrebtlima** [comment]
Grid styling out of order:
 
<img width="1435" alt="Screen Shot 2019-11-08 at 10 37 21 AM" src="https://user-images.githubusercontent.com/57111927/68488831-e520fd00-0213-11ea-834c-28bd54783f85.png">

http://bostond8dev.prod.acquia-sites.com/departments/digital-team

**Comment by davidrkupton** [comment]
I believe this occurs when there is some other issue on the page.
Jim did put a fix in, but that requires reworking the image backgrounds so I think we put a pin in this one and do it last if we need to.  We have the changes Jim made and I would just have to alter the background images.

**Comment by andrebtlima** [comment]
Moving this into our post-launch column.

**Comment by andrebtlima** [comment]
Ok so, this is still broken but I've noticed that certain guides are always appears as particular numbers:

Here is the digital team test page on dev:

![image](https://user-images.githubusercontent.com/57111927/69459244-58ac2980-0d3f-11ea-9618-a1d495197ff7.png)

And here is a test page I just made:

<img width="1434" alt="Screen Shot 2019-11-22 at 3 48 09 PM" src="https://user-images.githubusercontent.com/57111927/69459330-872a0480-0d3f-11ea-8b6b-5e03391b0724.png">

So it looks like the Winter in Boston guide is always appearing at 2 regardless of its position in the series of featured guides. 

Maybe useful for solving this issue.

**Comment by reillyzlab** [comment]
Still an issue with just winter in boston

**Comment by jimafisk** [comment]
@phillipbentonkelly and I worked on this today, hopefully we've finally put it to rest:

![output](https://user-images.githubusercontent.com/5913244/71533983-b6e1a480-28c9-11ea-90a4-bf1251a5cfdd.gif)

**Comment by reillyzlab** [comment]
Resolved

**Comment by andrebtlima** [comment]
Resolved so closing.
